kind: Deployment
apiVersion: apps/v1
metadata:
  name: test-devspaces
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-devspaces-app
  template:
    metadata:
      labels:
        app: test-devspaces-app
    spec:
      containers:
        - name: test-devspaces
          image: devspaces-image:latest
          command:
            - /bin/sleep
            - infinity
          resources:
            requests:
              memory: "50Mi"
              cpu: "10m"